language: go

go:
    - 1.8
    - 1.8.x
    - 1.9
    - 1.9.x
    - 1.10.x
    - 1.11.x

sudo: false

jobs:
  include:
    - stage: build
      script:  
        - go get -u github.com/golang/dep/...
        - dep ensure 
        - go install github.com/arbor-dev/arbor
    - stage: test
      script:
        - go test -v github.com/arbor-dev/arbor/tests

stages:
  - build
  - test

matrix:
  allow_failures:
    - go: 1.8.x
    - go: 1.9.x

notifications:
  email: false
